2023-02-11 00:29:05,666 INFO    MainThread:19060 [wandb_setup.py:_flush():68] Configure stats pid to 19060
2023-02-11 00:29:05,666 INFO    MainThread:19060 [wandb_setup.py:_flush():68] Loading settings from C:\Users\GCM\.config\wandb\settings
2023-02-11 00:29:05,667 INFO    MainThread:19060 [wandb_setup.py:_flush():68] Loading settings from E:\GIT_REPOS\LAB\Beetle_classifier\Train\wandb\settings
2023-02-11 00:29:05,667 INFO    MainThread:19060 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 00:29:05,667 INFO    MainThread:19060 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-11 00:29:05,667 INFO    MainThread:19060 [wandb_init.py:_log_setup():492] Logging user logs to .\wandb\run-20230211_002905-j3m1xy0w\logs\debug.log
2023-02-11 00:29:05,667 INFO    MainThread:19060 [wandb_init.py:_log_setup():493] Logging internal logs to .\wandb\run-20230211_002905-j3m1xy0w\logs\debug-internal.log
2023-02-11 00:29:05,668 INFO    MainThread:19060 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001FE730C4160>
2023-02-11 00:29:05,668 INFO    MainThread:19060 [wandb_init.py:init():532] calling init triggers
2023-02-11 00:29:05,668 INFO    MainThread:19060 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-02-11 00:29:05,668 INFO    MainThread:19060 [wandb_init.py:init():588] starting backend
2023-02-11 00:29:05,668 INFO    MainThread:19060 [wandb_init.py:init():592] setting up manager
2023-02-11 00:29:05,683 INFO    MainThread:19060 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-02-11 00:29:05,687 INFO    MainThread:19060 [wandb_init.py:init():599] backend started and connected
2023-02-11 00:29:05,696 INFO    MainThread:19060 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-02-11 00:29:05,699 INFO    MainThread:19060 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 00:29:05,700 INFO    MainThread:19060 [wandb_init.py:init():687] updated telemetry
2023-02-11 00:29:05,747 INFO    MainThread:19060 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-02-11 00:29:06,550 INFO    MainThread:19060 [wandb_run.py:_on_init():2134] communicating current version
2023-02-11 00:29:06,701 INFO    MainThread:19060 [wandb_run.py:_on_init():2143] got version response 
2023-02-11 00:29:06,701 INFO    MainThread:19060 [wandb_init.py:init():775] starting run threads in backend
2023-02-11 00:29:06,904 INFO    MainThread:19060 [wandb_run.py:_console_start():2114] atexit reg
2023-02-11 00:29:06,904 INFO    MainThread:19060 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-02-11 00:29:06,904 INFO    MainThread:19060 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-02-11 00:29:06,904 INFO    MainThread:19060 [wandb_run.py:_redirect():2059] Redirects installed.
2023-02-11 00:29:06,906 INFO    MainThread:19060 [wandb_init.py:init():817] run started, returning control to user process
2023-02-11 00:29:07,410 INFO    MainThread:19060 [wandb_run.py:_config_callback():1250] config_cb None None {'n_classes': 10, 'acc_task': 'multiclass', 'lr': 0.001}
2023-02-11 00:29:14,976 INFO    MainThread:19060 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-02-11 00:29:14,976 INFO    MainThread:19060 [wandb_init.py:_pause_backend():403] pausing backend
2023-02-11 00:39:37,565 INFO    MainThread:19060 [wandb_init.py:_resume_backend():408] resuming backend
2023-02-11 00:39:37,848 INFO    MainThread:19060 [wandb_run.py:_config_callback():1250] config_cb None None {'n_classes': 10, 'acc_task': 'multiclass', 'lr': 0.001}
2023-02-11 00:39:38,964 INFO    MainThread:19060 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-02-11 00:39:38,965 INFO    MainThread:19060 [wandb_init.py:_pause_backend():403] pausing backend
2023-02-11 00:39:44,031 WARNING MsgRouterThr:19060 [router.py:message_loop():77] message_loop has been closed
