2023-04-13 18:25:05,105 INFO    MainThread:26876 [wandb_setup.py:_flush():68] Configure stats pid to 26876
2023-04-13 18:25:05,105 INFO    MainThread:26876 [wandb_setup.py:_flush():68] Loading settings from C:\Users\GCM\.config\wandb\settings
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_setup.py:_flush():68] Loading settings from E:\GIT_REPOS\Beetle_classifier\Data_cleaning\Circle_classification\wandb\settings
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_init.py:_log_setup():492] Logging user logs to E:\GIT_REPOS\Beetle_classifier\Data_cleaning\Circle_classification\wandb\run-20230413_182505-bfrqz661\logs\debug.log
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_init.py:_log_setup():493] Logging internal logs to E:\GIT_REPOS\Beetle_classifier\Data_cleaning\Circle_classification\wandb\run-20230413_182505-bfrqz661\logs\debug-internal.log
2023-04-13 18:25:05,106 INFO    MainThread:26876 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002B54DFC0310>
2023-04-13 18:25:05,107 INFO    MainThread:26876 [wandb_init.py:init():532] calling init triggers
2023-04-13 18:25:05,107 INFO    MainThread:26876 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'batch_size': 2, 'epochs': 5, 'img_size': 224, 'seed': 42, 'pretrained': True, 'top_k_losses': 5, 'model_name': 'maxvit_rmlp_small_rw_224.sw_in1k', 'wandb_project': 'Ball_classifier', 'wandb_group': 'ambrosia_symbiosis', 'job_type': 'training'}
2023-04-13 18:25:05,107 INFO    MainThread:26876 [wandb_init.py:init():588] starting backend
2023-04-13 18:25:05,107 INFO    MainThread:26876 [wandb_init.py:init():592] setting up manager
2023-04-13 18:25:05,121 INFO    MainThread:26876 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-04-13 18:25:05,125 INFO    MainThread:26876 [wandb_init.py:init():599] backend started and connected
2023-04-13 18:25:05,134 INFO    MainThread:26876 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-04-13 18:25:05,137 INFO    MainThread:26876 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-04-13 18:25:05,137 INFO    MainThread:26876 [wandb_init.py:init():687] updated telemetry
2023-04-13 18:25:05,186 INFO    MainThread:26876 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-04-13 18:25:05,531 INFO    MainThread:26876 [wandb_run.py:_on_init():2134] communicating current version
2023-04-13 18:25:05,685 INFO    MainThread:26876 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-13 18:25:05,685 INFO    MainThread:26876 [wandb_init.py:init():775] starting run threads in backend
2023-04-13 18:25:06,146 INFO    MainThread:26876 [wandb_run.py:_console_start():2114] atexit reg
2023-04-13 18:25:06,147 INFO    MainThread:26876 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-13 18:25:06,147 INFO    MainThread:26876 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-13 18:25:06,147 INFO    MainThread:26876 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-13 18:25:06,148 INFO    MainThread:26876 [wandb_init.py:init():817] run started, returning control to user process
2023-04-13 18:25:08,515 INFO    MainThread:26876 [jupyter.py:_save_ipynb():390] looking for notebook: GIT_REPOS/Beetle_classifier/Data_cleaning/Circle_classification/Train_ball_classifier.ipynb
2023-04-13 18:25:08,516 INFO    MainThread:26876 [wandb_init.py:_pause_backend():403] pausing backend
2023-04-13 20:06:25,205 WARNING MsgRouterThr:26876 [router.py:message_loop():77] message_loop has been closed
